server:
  port: 8282

# Uncomment to enable the use of a load balanced RestTemplate instead of Feign
#races:
#  rest:
#   enabled: true
stubrunner:
  idsToServiceIds:
    ocr-participants: participants
  ids: 'com.ryanjbaxter.spring.cloud:ocr-participants:+:stubs'
  repositoryRoot: https://oss.sonatype.org/content/repositories/snapshots/
  stubs-mode: remote
  snapshot-check-skip: true